import { defineConfig } from "vitepress";

export default defineConfig({
    title: "Gnoblin",
    description: "Build a floating Wayland desktop with Gnoblin's compositor tools and public APIs.",
    base: "/gnoblin/",
    cleanUrls: true,
    themeConfig: {
        nav: [
            { text: "Get started", link: "/" },
            { text: "Config", link: "/config" },
            { text: "Shell development", link: "/shell-integration" },
            { text: "Contributing", link: "/source-development" },
            { text: "GitHub", link: "https://github.com/kierandrewett/gnoblin" },
        ],
        search: { provider: "local" },
        outline: { level: [2, 3] },
        editLink: {
            pattern: "https://github.com/kierandrewett/gnoblin/edit/main/docs/:path",
            text: "Edit this page on GitHub",
        },
        socialLinks: [{ icon: "github", link: "https://github.com/kierandrewett/gnoblin" }],
        sidebar: [
            {
                text: "Get started",
                items: [
                    { text: "Welcome", link: "/" },
                    {
                        text: "Installation",
                        collapsed: true,
                        items: [
                            { text: "Choose your system", link: "/installation" },
                            { text: "Fedora", link: "/install-fedora" },
                            { text: "Debian / Ubuntu", link: "/install-debian" },
                            { text: "NixOS", link: "/install-nixos" },
                            { text: "Build from source", link: "/install-source" },
                        ],
                    },
                    { text: "Choose a shell", link: "/bring-your-own-shell" },
                    { text: "Build your desktop", link: "/build-a-desktop" },
                    { text: "Troubleshooting", link: "/troubleshooting" },
                ],
            },
            {
                text: "Config API",
                link: "/config",
                items: [
                    {
                        text: "gnoblin.configure",
                        link: "/config/configure",
                        items: [
                            { text: "shell", link: "/config/configure/shell" },
                            { text: "window_management", link: "/config/configure/window_management" },
                            { text: "compositor", link: "/config/configure/compositor" },
                            {
                                text: "input",
                                link: "/config/configure/input",
                                items: [
                                    { text: "mouse", link: "/config/configure/input/mouse" },
                                    { text: "touchpad", link: "/config/configure/input/touchpad" },
                                    { text: "keyboard", link: "/config/configure/input/keyboard" },
                                ],
                            },
                            { text: "input_sources", link: "/config/configure/input_sources" },
                            { text: "permissions", link: "/config/configure/permissions" },
                            { text: "layer_shell", link: "/config/configure/layer_shell" },
                            { text: "protocols", link: "/config/configure/protocols" },
                            { text: "frame_renderers", link: "/config/configure/frame_renderers" },
                            { text: "cursor", link: "/config/configure/cursor" },
                            { text: "shortcuts", link: "/config/configure/shortcuts" },
                            { text: "autostart", link: "/config/configure/autostart" },
                        ],
                    },
                    { text: "gnoblin.window_rule", link: "/config/window_rule" },
                    { text: "gnoblin.animation", link: "/config/animation" },
                    { text: "gnoblin.remove_animation", link: "/config/remove_animation" },
                    { text: "gnoblin.permission_rule", link: "/config/permission_rule" },
                    { text: "gnoblin.load", link: "/config/load" },
                    { text: "gnoblin.snapshot", link: "/config/snapshot" },
                    { text: "gnoblin.array", link: "/config/array" },
                ],
            },
            {
                text: "Configuration guides",
                collapsed: true,
                items: [
                    { text: "Files and load order", link: "/guides/files_and_load_order" },
                    { text: "Shortcuts", link: "/guides/shortcuts" },
                    { text: "Autostart", link: "/guides/autostart" },
                    { text: "Window rules", link: "/guides/window_rules" },
                    { text: "Window effects", link: "/guides/window_effects" },
                    { text: "Window frames", link: "/guides/window_frames" },
                    { text: "Animations", link: "/guides/animations" },
                    { text: "Shaders", link: "/guides/shaders" },
                    { text: "Cursors", link: "/guides/cursors" },
                    { text: "Permissions", link: "/guides/permissions" },
                    { text: "Session settings", link: "/guides/session_settings" },
                    { text: "Window menu", link: "/guides/window_menu" },
                    { text: "Window state shortcuts", link: "/guides/window_state_shortcuts" },
                    { text: "Window snapping", link: "/guides/window_snapping" },
                ],
            },
            {
                text: "Recipes",
                link: "/recipes/",
                collapsed: true,
                items: [
                    {
                        text: "Desktop setup",
                        collapsed: true,
                        items: [
                            { text: "Build a small desktop", link: "/recipes/small-desktop" },
                            { text: "Organize a growing config", link: "/recipes/organize-config-files" },
                        ],
                    },
                    {
                        text: "Input workflows",
                        collapsed: true,
                        items: [
                            { text: "Set up a laptop for two keyboard layouts", link: "/recipes/laptop-input" },
                            { text: "Set up a pen display", link: "/recipes/pen-display-workflow" },
                        ],
                    },
                    {
                        text: "Windows and workspaces",
                        collapsed: true,
                        items: [
                            { text: "Set up a focused writing workspace", link: "/recipes/writing-workspace" },
                        ],
                    },
                    {
                        text: "Privacy and accessibility",
                        collapsed: true,
                        items: [
                            { text: "Prepare remote support access", link: "/recipes/remote-support" },
                            { text: "Make pointer feedback easier to see", link: "/recipes/pointer-feedback" },
                        ],
                    },
                ],
            },
            {
                text: "Shell development",
                collapsed: true,
                items: [
                    { text: "Integration", link: "/shell-integration" },
                    { text: "Compositor bridge", link: "/compositor-bridge" },
                    { text: "Bridge examples", link: "/bridge-examples" },
                    { text: "Wayland protocols", link: "/wayland-protocols" },
                    { text: "Session locking", link: "/session-lock" },
                    { text: "User scripts", link: "/user-scripts" },
                    { text: "Background blur", link: "/background-effects" },
                    { text: "Blur fades", link: "/blur-fades" },
                    { text: "Effect rendering", link: "/effects-rendering" },
                    { text: "Activation", link: "/focus-transfer" },
                    { text: "Launch feedback", link: "/launch-feedback" },
                    { text: "Frame architecture", link: "/window-frame-renderers" },
                    { text: "Write a renderer", link: "/frame-renderer-api" },
                    { text: "Native and external UI", link: "/native-ui-removal" },
                    { text: "Console", link: "/developer-console" },
                ],
            },
            {
                text: "Contributing",
                collapsed: true,
                items: [
                    { text: "Source development", link: "/source-development" },
                    { text: "Devkit", link: "/devkit" },
                    { text: "Testing", link: "/testing" },
                    { text: "Desktop verification", link: "/real-hardware-verification" },
                    { text: "Formatting", link: "/code-quality" },
                    { text: "CLI development", link: "/cli-development" },
                    { text: "Packaging", link: "/distribution" },
                    { text: "Documentation", link: "/documentation-site" },
                    { text: "Archive", link: "/archive" },
                ],
            },
        ],
        docFooter: { prev: "Previous page", next: "Next page" },
    },
    markdown: {
        theme: {
            light: "github-light",
            dark: "github-dark",
        },
    },
});
