# Make the pinned sources ready for the Meson builds. Needs cmake/source-lib.cmake.
#
# Source mode "checkout" uses the git submodules. Source mode "release-archive" unpacks the tarballs in sources/.

# Extract an archive that has one top-level directory, and put the contents of that directory at destination.
function(gnoblin_extract_stripped archive destination)
  set(raw "${destination}.raw")
  file(REMOVE_RECURSE "${raw}")
  file(MAKE_DIRECTORY "${raw}")
  file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${raw}")
  file(GLOB top LIST_DIRECTORIES true "${raw}/*")
  list(LENGTH top count)
  if(NOT count EQUAL 1 OR NOT IS_DIRECTORY "${top}")
    file(REMOVE_RECURSE "${raw}" "${destination}")
    message(FATAL_ERROR "Invalid release source: ${archive} must hold one top-level directory")
  endif()
  file(REMOVE_RECURSE "${destination}")
  file(RENAME "${top}" "${destination}")
  file(REMOVE_RECURSE "${raw}")
endfunction()

# The first line of a file, or the empty string when the file is missing.
function(gnoblin_read_marker out path)
  set(value "")
  if(EXISTS "${path}")
    file(READ "${path}" value)
    string(STRIP "${value}" value)
  endif()
  set(${out} "${value}" PARENT_SCOPE)
endfunction()

function(gnoblin_prepare_gsettings_schemas mode)
  gnoblin_pin(version gsettings-desktop-schemas version)
  gnoblin_pin(revision gsettings-desktop-schemas commit)
  set(source_root "${GNOBLIN_ROOT}/build/source-inputs/gsettings-desktop-schemas-pinned")
  set(schema_file "${source_root}/schemas/org.gnome.desktop.wm.keybindings.gschema.xml.in")

  if(mode STREQUAL "release-archive")
    set(archive "${GNOBLIN_ROOT}/sources/gsettings-desktop-schemas-${version}.tar.xz")
    if(IS_DIRECTORY "${source_root}")
      gnoblin_read_marker(marker "${source_root}/GNOBLIN_SOURCE_REVISION")
      if(marker STREQUAL revision AND EXISTS "${schema_file}")
        return()
      endif()
      gnoblin_git(head rc -C "${source_root}" rev-parse HEAD)
      gnoblin_git(changes rc -C "${source_root}" status --porcelain)
      if(head STREQUAL revision AND changes STREQUAL "" AND rc EQUAL 0)
        return()
      endif()
      message(FATAL_ERROR
        "refusing to replace existing schema source without the pinned revision marker: ${source_root}")
    endif()
    if(NOT EXISTS "${archive}")
      message(FATAL_ERROR "missing pinned schema source archive: ${archive}")
    endif()
    file(MAKE_DIRECTORY "${GNOBLIN_ROOT}/build/source-inputs")
    string(RANDOM LENGTH 6 suffix)
    set(extracted "${GNOBLIN_ROOT}/build/source-inputs/.gsettings-desktop-schemas.${suffix}")
    gnoblin_extract_stripped("${archive}" "${extracted}")
    gnoblin_read_marker(actual "${extracted}/GNOBLIN_SOURCE_REVISION")
    if(NOT actual STREQUAL revision)
      file(REMOVE_RECURSE "${extracted}")
      message(FATAL_ERROR "schema source archive revision is '${actual}', expected '${revision}'")
    endif()
    if(NOT EXISTS "${extracted}/schemas/org.gnome.desktop.wm.keybindings.gschema.xml.in")
      file(REMOVE_RECURSE "${extracted}")
      message(FATAL_ERROR "schema source archive is missing the pinned WM schema")
    endif()
    file(RENAME "${extracted}" "${source_root}")
    return()
  endif()

  if(NOT mode STREQUAL "checkout")
    message(FATAL_ERROR "unknown source mode: ${mode}")
  endif()
  gnoblin_read_marker(marker "${source_root}/GNOBLIN_SOURCE_REVISION")
  if(IS_DIRECTORY "${source_root}" AND marker STREQUAL revision AND EXISTS "${schema_file}")
    return()
  endif()
  gnoblin_git(ignored not_git -C "${source_root}" rev-parse --git-dir)
  if(EXISTS "${source_root}" AND not_git)
    message(FATAL_ERROR "schema source cache is not a Git checkout: ${source_root}")
  endif()
  if(not_git)
    file(MAKE_DIRECTORY "${GNOBLIN_ROOT}/build/source-inputs")
    gnoblin_run(git clone --quiet --filter=blob:none
      https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas.git "${source_root}")
  endif()
  gnoblin_git(changes rc -C "${source_root}" status --porcelain)
  if(NOT changes STREQUAL "")
    message(FATAL_ERROR "pinned schema source cache contains local changes: ${source_root}")
  endif()
  gnoblin_git(head rc -C "${source_root}" rev-parse HEAD)
  if(NOT head STREQUAL revision)
    gnoblin_run(git -C "${source_root}" fetch --quiet --depth=1 origin "${revision}")
    gnoblin_run(git -C "${source_root}" checkout --quiet --detach "${revision}")
  endif()
  gnoblin_git(actual rc -C "${source_root}" rev-parse HEAD)
  if(NOT actual STREQUAL revision)
    message(FATAL_ERROR "schema source checkout is at ${actual}, expected ${revision}")
  endif()
endfunction()

# Unpack the release archives of the named projects into subprojects/. A project that has a meson.build is done.
function(gnoblin_unpack_release_sources)
  foreach(name IN LISTS ARGN)
    set(destination "${GNOBLIN_ROOT}/subprojects/${name}")
    if(EXISTS "${destination}/meson.build")
      continue()
    endif()
    set(incomplete FALSE)
    if(IS_SYMLINK "${destination}" OR (EXISTS "${destination}" AND NOT IS_DIRECTORY "${destination}"))
      set(incomplete TRUE)
    elseif(IS_DIRECTORY "${destination}")
      file(GLOB entries "${destination}/*")
      if(entries)
        set(incomplete TRUE)
      endif()
    endif()
    if(incomplete)
      message(FATAL_ERROR "Incomplete release source: subprojects/${name}. Remove it before retrying.")
    endif()
    file(GLOB archives "${GNOBLIN_ROOT}/sources/${name}-*.tar.xz")
    list(LENGTH archives archive_count)
    if(NOT archive_count EQUAL 1)
      message(FATAL_ERROR "Expected one ${name} source archive in sources/.")
    endif()
    file(MAKE_DIRECTORY "${GNOBLIN_ROOT}/subprojects")
    string(RANDOM LENGTH 6 suffix)
    set(temporary "${GNOBLIN_ROOT}/subprojects/.${name}.extract.${suffix}")
    gnoblin_extract_stripped("${archives}" "${temporary}")
    if(NOT EXISTS "${temporary}/meson.build")
      file(REMOVE_RECURSE "${temporary}")
      message(FATAL_ERROR "Invalid release source: ${archives}")
    endif()
    file(REMOVE_RECURSE "${destination}")
    file(RENAME "${temporary}" "${destination}")
  endforeach()
endfunction()

# Prepare the sources of the named projects. With no names, prepare both Meson projects.
function(gnoblin_prepare_sources mode)
  set(projects ${ARGN})
  if(NOT projects)
    set(projects ${GNOBLIN_SOURCE_PROJECTS})
  endif()
  if(projects STREQUAL "gsettings-desktop-schemas")
    gnoblin_prepare_gsettings_schemas("${mode}")
    return()
  endif()
  foreach(name IN LISTS projects)
    if(name STREQUAL "gsettings-desktop-schemas")
      message(FATAL_ERROR "gsettings-desktop-schemas must be prepared on its own")
    endif()
    if(NOT name IN_LIST GNOBLIN_SOURCE_PROJECTS)
      message(FATAL_ERROR "Unknown source project: ${name}")
    endif()
  endforeach()
  if(mode STREQUAL "release-archive")
    gnoblin_unpack_release_sources(${projects})
    return()
  endif()
  if(NOT mode STREQUAL "checkout")
    message(FATAL_ERROR "Unknown source mode: ${mode}")
  endif()

  foreach(name IN LISTS projects)
    gnoblin_run_in_root(git submodule sync --recursive -- "subprojects/${name}")
    gnoblin_git(actual_root rc -C "${GNOBLIN_ROOT}/subprojects/${name}" rev-parse --show-toplevel)
    get_filename_component(expected_root "${GNOBLIN_ROOT}/subprojects/${name}" REALPATH)
    if(NOT actual_root STREQUAL expected_root)
      gnoblin_run_in_root("${GNOBLIN_ROOT}/scripts/checkout-submodules-with-retry.sh" -- "subprojects/${name}")
    endif()
  endforeach()
  gnoblin_ensure_release_subprojects(${projects})
  foreach(name IN LISTS projects)
    gnoblin_pin(tag "${name}" version)
    gnoblin_state_require("${name}" "${tag}")
    execute_process(COMMAND "${GNOBLIN_ROOT}/scripts/list-tarball-sources.sh" "${name}" --prepare
      WORKING_DIRECTORY "${GNOBLIN_ROOT}" OUTPUT_QUIET COMMAND_ERROR_IS_FATAL ANY)
    gnoblin_state_record("${name}" "${tag}")
  endforeach()
endfunction()

function(gnoblin_run_in_root)
  execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${GNOBLIN_ROOT}" COMMAND_ERROR_IS_FATAL ANY)
endfunction()

# Apply the patch series of one component when its inputs changed since the last run. The inputs are the version pins,
# the patches, the overlay manifests and the overlay sources. The stamp holds their hash. A checkout that sits on the
# bare tag has no patches yet, so it is always patched.
function(gnoblin_component_sources name build_root)
  if(name STREQUAL "mutter")
    # Check the pinned fork before the patch run resets it.
    gnoblin_ensure_release_subprojects(mutter)
  endif()
  set(inputs "${GNOBLIN_ROOT}/gnome-versions.json")
  file(GLOB_RECURSE patches "${GNOBLIN_ROOT}/patches/${name}/*.patch")
  list(SORT patches)
  list(APPEND inputs ${patches})
  if(name STREQUAL "xdg-desktop-portal-gnome")
    list(APPEND inputs "${GNOBLIN_ROOT}/patches/portal-dependencies/libgxdp/0001-gtk-4.20-compat.patch")
  endif()
  file(GLOB_RECURSE manifests "${GNOBLIN_ROOT}/src/manifest")
  list(SORT manifests)
  foreach(manifest IN LISTS manifests)
    list(APPEND inputs "${manifest}")
    get_filename_component(feature_dir "${manifest}" DIRECTORY)
    file(READ "${manifest}" text)
    string(REGEX MATCHALL "[^\n]+" lines "${text}")
    foreach(line IN LISTS lines)
      string(REGEX MATCHALL "[^ \t]+" fields "${line}")
      list(LENGTH fields field_count)
      if(field_count LESS 2)
        continue()
      endif()
      list(GET fields 0 entry_project)
      list(GET fields 1 source)
      if(entry_project STREQUAL name)
        list(APPEND inputs "${feature_dir}/${source}")
      endif()
    endforeach()
  endforeach()

  # The same text "sha256sum <inputs> | sha256sum" hashed, so a stamp from the old script stays valid.
  set(listing "")
  foreach(input IN LISTS inputs)
    file(SHA256 "${input}" digest)
    string(APPEND listing "${digest}  ${input}\n")
  endforeach()
  string(SHA256 signature "${listing}")

  set(stamp "${build_root}/${name}.patch-inputs.sha256")
  gnoblin_read_marker(recorded "${stamp}")
  gnoblin_pin(tag "${name}" version)
  set(subproject "${GNOBLIN_ROOT}/subprojects/${name}")
  gnoblin_git(head rc -C "${subproject}" rev-parse HEAD)
  gnoblin_git(pinned rc -C "${subproject}" rev-parse "${tag}^{commit}")
  if(NOT EXISTS "${stamp}" OR NOT recorded STREQUAL signature OR head STREQUAL pinned)
    gnoblin_apply_patches("${name}")
    file(WRITE "${stamp}" "${signature}\n")
  endif()
endfunction()
